FROM containerbase/buildpack@sha256:7a445e77431e8acb20c48b91727f5509ff94f8019d31635218d4d6e22fd9b2ac

# renovate: datasource=docker versioning=docker
RUN install-tool node 14.16.1 \
# renovate: datasource=npm
  && install-tool yarn 1.22.10